{% set version = "5.2.2" %}

package:
  name: iris-ued
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/iris-ued/iris-ued-{{ version }}.tar.gz
  sha256: 2980bf192f4f716da42f6a208569cc0c09aa3babe2b3c146d0728a1b60078261

build:
  number: 2
  skip: True  # [py<36]
  entry_points:
    - iris = iris.gui:run
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.12,<2
    - scipy >=1.0.0,<2
    - h5py >=2.10.0,<3
    - pyqt >=5,<6
    - qdarkstyle >=2.8, <3
    - scikit-ued >=2.0.3, <3
    - pyqtgraph >=0.11,<1
    - npstreams >=1.6.2,<2
    - crystals >=1.1.2, <2
      # missing requirement in qdarkstyle: 
      #    github.com/conda-forge/qdarkstyle-feedstock/issues/12
    - qtpy >=1.9, <2

test:
  imports:
    - iris
    - iris.gui

about:
  home: http://iris-ued.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Ultrafast electron scattering data exploration
  description: |
    Iris is both a library for interacting with ultrafast electron scattering data, 
    as well as a GUI frontend for interactively exploring this data.
  doc_url: 'https://iris-ued.readthedocs.io/'
  dev_url: 'https://github.com/LaurentRDC/iris-ued'

extra:
  recipe-maintainers: 
    - LaurentRDC
