{% set version = "5.3.5" %}

package:
  name: iris-ued
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/iris-ued/iris-ued-{{ version }}.tar.gz
  sha256: 04cd82cae96f99f2cf52c5b92903b9f1780ba44253817271e302ca2f112fed29

build:
  noarch: python
  number: 0
  entry_points:
    - iris = iris.gui:run
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - numpy >=1.17,<2
    - scipy >=1.0.0,<2
    - h5py >=2.10.0,<4
    - pyqt >=5,<6
    - qdarkstyle >=2.8.1, <3
    - scikit-ued >=2.1.3, <3
    - pyqtgraph >=0.11,<1
    - npstreams >=1.6.5,<2
    - crystals >=1.3.0, <2

test:
  requires:
    - pytest >= 6
  imports:
    - iris
    - iris.gui
  commands:
    - pytest --pyargs iris

about:
  home: http://iris-ued.readthedocs.io
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Ultrafast electron scattering data exploration
  description: |
    Iris is both a library for interacting with ultrafast electron scattering data, 
    as well as a GUI frontend for interactively exploring this data.
  doc_url: https://iris-ued.readthedocs.io/
  dev_url: https://github.com/LaurentRDC/iris-ued

extra:
  recipe-maintainers:
    - LaurentRDC
