{% set version = "5.2.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "69a6f0fa224029d4d4f90d30b69f293dce68fd33db5eb0d538b29a052caec5de" %}

package:
  name: 'iris-ued'
  version: '{{ version }}'

source:
  fn: 'iris-ued-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/i/iris-ued/iris-ued-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  skip: True  # [ py<36 or osx ]
  number: 0
  entry_points:
    - iris = iris.gui:run
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.12, <2
    - scipy >=1.0.0, <2
    - h5py >=2.6.0, <3
    - pyqt >=5, <6
    - qdarkstyle ==2.7
    - scikit-ued ==2.0.1
    - pyqtgraph >=0.10, <1
    - npstreams ==1.6.1
    - crystals ==0.6.6

test:
  imports:
    - iris
    - iris.gui

about:
  home: http://iris-ued.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: 'LICENSE.txt'
  summary: Ultrafast electron scattering data exploration
  description: |
    Iris is both a library for interacting with ultrafast electron scattering data, 
    as well as a GUI frontend for interactively exploring this data.
  doc_url: 'https://iris-ued.readthedocs.io/'
  dev_url: 'https://github.com/LaurentRDC/iris-ued'

extra:
  recipe-maintainers: 
    - LaurentRDC
