# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gLu4yLejsD0b+oZUxLXDMPw5GG4JBUo9rsm5d/eqfbDKIcJpMP4TG902IQQM6FbdjTV+njoBnVhR+QF65Ma5e9JxWyTtz82dqPt0znNInM02eDo9bL2yN3H2pqA0toa0CDJPpiUUJiBQGI+jQE1CUeAd8E4ahCA0cZ9mrgC1P+98iGkVAXs7u82UUJIby47sY4D+SWltb0L44+oLtxqjbgSDpJ9O7OlNVndTbN0u8rH0NdNvR5qybW01hO56b2sLM+r+heRAcy1+WpuL11BHALAzR+m4VZk68EssYrPa3YUC9oyqvbvyt7o9/6ptxdrKV+zuIyIUlYsmgF+pEbl0/gW+PImTPkoPPzoJW6iYLDmuPhLrJEhgnmQv4nOFbUpUDS1s+Bw4dX1auMaIcGDVfHrNT5hKTr/ydgsW0rFmJI90rWGtVWsU+Rd2q4nWqIwUSEIQv2wWiblR0LbvwnvG3wscnwVFD2vrSFd4+hJEKm0OufBczuzZMJ3qXVdGth4uksDBqah2jv7aDKB+26pNPEt9t5ptyjNgbTy0Cr1ph6hSdJaBDOm5N5eGgggItB0lh0T7Rib4aPuHJO9hivYrUi+f/UwDC9ytwuDDivUNd8CnhPSU1ywI0UTC6UEKg0/QFazw6bGBvgrmkUb4Q9X/Vt8v9x3Mm3NunsPhmm5lBGs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml